### ISSUE TITLE
Highlight color on current active buffer?

### ISSUE THREAD

**Issue by MrAvantiC** [taohex/lightline-buffer#1]
Hey,

first of all: thanks for the work you put into this plugin!

I wanted to know, is it possible to change the color of the currently active buffer?

These are my current Lightline/-buffer settings:
```
let g:lightline = {
      \ 'colorscheme': 'wombat',
      \ 'active': {
      \   'left': [ [ 'mode', 'paste' ],
      \             [ 'fugitive', 'filename' ] ]
      \ },
      \ 'component_function': {
      \   'fugitive': 'LightlineFugitive',
      \   'readonly': 'LightlineReadonly',
      \   'modified': 'LightlineModified',
      \   'bufferbefore': 'lightline#buffer#bufferbefore',
      \   'bufferafter': 'lightline#buffer#bufferafter',
      \   'bufferinfo': 'lightline#buffer#bufferinfo',   
      \   'filename': 'LightlineFilename'
      \ },
      \ 'separator': { 'left': "\ue0b0", 'right': "\ue0b2" },
      \ 'subseparator': { 'left': "\ue0b1", 'right': "\ue0b3" },
      \ 'tabline': {
        \ 'left': [ [ 'bufferinfo' ], [ 'bufferbefore', 'buffercurrent', 'bufferafter' ], ],
        \ 'right': [ [ 'close' ], ],
        \ },
      \ 'component_expand': {
        \ 'buffercurrent': 'lightline#buffer#buffercurrent2',
        \ },
      \ }

function! LightlineModified()
  if &filetype == "help"
    return ""
  elseif &modified
    return "+"
  elseif &modifiable
    return ""
  else
    return ""
  endif
endfunction

function! LightlineReadonly()
  if &filetype == "help"
    return ""
  elseif &readonly
    return "\ue0a2"
  else
    return ""
  endif
endfunction

function! LightlineFugitive()
  if exists("*fugitive#head")
    let branch = fugitive#head()
    return branch !=# "" ? "\ue0a0 ".branch : ""
  endif
  return ''
endfunction

function! LightlineFilename()
  return ('' != LightlineReadonly() ? LightlineReadonly() . ' ' : '') .
       \ ('' != expand('%:t') ? expand('%:t') : '[No Name]') .
       \ ('' != LightlineModified() ? ' ' . LightlineModified() : '')
endfunction
" }}}

"Lightline-Buffer settings
set showtabline=2   " always show tabline
" remap arrow keys
nnoremap <Left> :bprev<CR>
nnoremap <Right> :bnext<CR>

" lightline-buffer settings
let g:lightline_buffer_logo = ' '
let g:lightline_buffer_readonly_icon = ''
let g:lightline_buffer_modified_icon = '✭'
let g:lightline_buffer_git_icon = ' '
let g:lightline_buffer_ellipsis_icon = '..'
let g:lightline_buffer_expand_left_icon = '◀ '
let g:lightline_buffer_expand_right_icon = ' ▶'
let g:lightline_buffer_active_buffer_left_icon = ''
let g:lightline_buffer_active_buffer_right_icon = ''
let g:lightline_buffer_separator_icon = ' '

let g:lightline_buffer_show_bufnr = 1
let g:lightline_buffer_rotate = 0
let g:lightline_buffer_fname_mod = ':t'
let g:lightline_buffer_excludes = ['vimfiler']

let g:lightline_buffer_maxflen = 30
let g:lightline_buffer_maxfextlen = 3
let g:lightline_buffer_minflen = 16
let g:lightline_buffer_minfextlen = 3
let g:lightline_buffer_reservelen = 20
```

What would I have to add to the vimrc to enable colors?

**Comment by taohex** [comment]
Hi,
The easiest way is modifying the color theme file.
For example, if you are using the 'wombat' color theme, you can modify `~/.config/nvim/bundle/repos/github.com/itchyny/lightline.vim/autoload/lightline/colorscheme/wombat.vim` and change the line `let s:p.tabline.tabsel = [ [ s:base3, s:base03 ] ]`.
The way I am more recommended is writing your own customized color theme as a lightline plugin. You can clone my [lightline-solarized](https://github.com/taohex/lightline-solarized) as a staring point and modify it. Then modify `~/.config/nvim/bundle/repos/github.com/taohex/lightline-solarized/autoload/lightline/colorscheme/lightline_solarized_dark.vim`.
More comments are welcome!
Thank you!

**Comment by MrAvantiC** [comment]
Hey,

thanks for your response.
I tried changing the `tabline.tabsel`-line in the colorscheme but it had no effect.
Just to make sure I was in the right file I tried changing different values, for example `tabline.left/midde/right`, and I could observe visual changes in the colorscheme. But for some reason the currently active buffer still looks the same.
By the way I also tried this your lightline-solarized theme and it didn't work either.

Maybe there is an option that needs to be activated to enable this feature of styling the active buffer? But I'm just shooting in the dark here to be honest... ;)

**Comment by taohex** [comment]
OK, I will look into this later. Thank you!

**Comment by pwntester** [comment]
Hi,

I had the same problem, the tabline does not highlight the current buffer

Thanks,
A

**Comment by taohex** [comment]
Hi @pwntester ,
Which of the following do you mean?
1. You want to modify the color in the color scheme.
2. All buffers have the same color, so you can't determine which is the current buffer.
Thanks!

**Comment by pwntester** [comment]
Hi,

The second one, all buffers have the same color.
![snapshot](http://i.imgur.com/dPUb0Qn.png)

Thanks,
A

**Comment by taohex** [comment]
Which color scheme are you using?

**Comment by pwntester** [comment]
I use OSX with iTerm2 and Solarized dark theme. For vim, I use `GertjanReynaert/cobalt2-vim-theme`. I dont have a color scheme set up for `lightline`.

I just tried using `Solarized` for everything: `iterm2`, `vim` and `lightline` and got the same issue, active buffer is not highlighted

**Comment by MrAvantiC** [comment]
@taohex As I said in my comment earlier, I also tried your suggestion with your very own "lightline-solarized" theme that you mentioned earlier and it didn't work.

**Comment by antoineco** [comment]
I'm also facing that issue, regardless of the vim/lightline/terminal color scheme I use, all I see is two "**|**" surrounding the active buffer name.

![lightline-buffer](https://cloud.githubusercontent.com/assets/3299086/20803476/aabebf1a-b7ef-11e6-9786-5d15cbbba2c6.png)

*great plugin btw!*

**Comment by pwntester** [comment]
I checked the code and saw that you are basically creating the before, current and after strings and concatenating them in the same lightline subcomponent, which should always be rendered with the same syntax highlight. 

I ended up writing a simple component function that uses the lightline tab components to show the buffer line reusing the lightline components and styles. You may want to use this approach for your plugin since my function is quite simple but it works fine and easy. The function is described [here](https://github.com/itchyny/lightline.vim/issues/205)

**Comment by taohex** [comment]
Hi all,
Finally I figure out the problem. I missed the below line in README.

```sh
    \ 'component_type': {
        \ 'buffercurrent': 'tabsel',
        \ },
```

Please add it, and I have updated the README. Thank you very much for your feedback!

**Comment by Machiel** [comment]
Great, that fixed it for me :) Thanks!

**Comment by w163** [comment]
It works!
