### ISSUE TITLE
Replacing X in right corner

### ISSUE THREAD

**Issue by FilipMiletic** [taohex/lightline-buffer#3]
Is there any way to replace close sign in top right corner with something more useful since I do not use mouse, so clicking is disabled and I do not see point in saying X there, I would rather it saying "buffers". Anyway, I had hard time figuring out what to edit in your code, (it's my bad, I am not that great with VimL), so is there any advice or direction where to look at for that change? I know how to do it with default's vim buffer line, but here it is a bit different.

**Comment by taohex** [comment]
What do you want to show there? Do you mean displaying "buffers" without anything else?

**Comment by FilipMiletic** [comment]
For example, yes.

**Comment by taohex** [comment]
Yes, you can try this configuration:

```
let g:lightline = {
    \ 'tabline': {
        \ 'left': [ [ 'bufferinfo' ], [ 'bufferbefore', 'buffercurrent', 'bufferafter' ], ],
        \ 'right': [ [ 'buffers' ], ],
        \ },
    \ 'component_expand': {
        \ 'buffercurrent': 'lightline#buffer#buffercurrent2',
        \ },
    \ 'component_type': {
        \ 'buffercurrent': 'tabsel',
        \ },
    \ 'component_function': {
        \ 'bufferbefore': 'lightline#buffer#bufferbefore',
        \ 'bufferafter': 'lightline#buffer#bufferafter',
        \ 'bufferinfo': 'lightline#buffer#bufferinfo',
        \ },
    \ 'component': {
        \ 'buffers': 'buffers',
        \ },
    \ }
```

**Comment by taohex** [comment]
![Alt text](http://g.gravizo.com/g?
  digraph G {
    aize ="4,4";
    main [shape=box];
    main -> parse [weight=8];
    parse -> execute;
    main -> init [style=dotted];
    main -> cleanup;
    execute -> { make_string; printf}
    init -> make_string;
    edge [color=red];
    main -> printf [style=bold,label="100 times"];
    make_string [label="make a string"];
    node [shape=box,style=filled,color=".7 .3 1.0"];
    execute -> compare;
  }
)

**Comment by FilipMiletic** [comment]
Oh my god, I am blind! Thank you very much, and sorry for taking your time! Peace

**Comment by taohex** [comment]
😄

**Comment by taohex** [comment]
<img src='http://g.gravizo.com/g?
@startuml;

actor User;
participant "First Class" as A;
participant "Second Class" as B;
participant "Last Class" as C;

User -> A: DoWork;
activate A;

A -> B: Create Request;
activate B;

B -> C: DoWork;
activate C;

C --> B: WorkDone;
destroy C;

B --> A: Request Created;
deactivate B;

A --> User: Done;
deactivate A;

@enduml
'>
