### ISSUE TITLE
modification marker "+" stays after saving

### ISSUE THREAD

**Issue by fdietze** [taohex/lightline-buffer#4]
The modification marker "+" next to a filename stays after saving. It only goes away after switching to another buffer.

**Comment by taohex** [comment]
Hi, thank you. But I can't reproduce this. Can you show me how to reproduce?

**Comment by fdietze** [comment]
I broke it down to this small .vimrc (I'm using neovim):
```vim
set nocompatible
set laststatus=2
set hidden
set noshowmode


call plug#begin('~/.vim/bundle')
Plug 'itchyny/lightline.vim'
Plug 'mgee/lightline-bufferline'
call plug#end()

let g:lightline = {
      \ 'active': {
      \   'left': [ [ 'mode' ], [  'buffers' ]],
      \ },
      \ 'component_expand': {
      \   'buffers' : 'lightline#bufferline#buffers'
      \ },
      \ 'component_type': {
      \   'buffers': 'tabsel'
      \ },
      \ }
```

To reproduce:

1. Open two files: `vim a b` (should start with the current buffer = a)
2. Insert new line: `o<Esc>`
3. Switch buffer two times `:bn` `:bn`
4. Save `:w`

The plus is still displayed for buffer a, even though it is not modified anymore. It disappears with another buffer change `:bn`.

Thanks for looking into this.

**Comment by taohex** [comment]
Hi,
I have reproduced your issue, but you are using other plugin in your `.vimrc`. In my plugin I can't reproduce it. How about trying the below `.vimrc` to see if my plugin have the same issue?

```vimscript
set nocompatible
set hidden
set showtabline=2

call plug#begin('~/.vim/bundle')
Plug 'itchyny/lightline.vim'
Plug 'taohex/lightline-buffer'
call plug#end()

let g:lightline = {
    \ 'active': {
        \ 'left': [ ['mode'], [ 'bufferinfo' ], [ 'bufferbefore', 'buffercurrent', 'bufferafter' ], ],
        \ },
    \ 'component_expand': {
        \ 'buffercurrent': 'lightline#buffer#buffercurrent2',
        \ },
    \ 'component_type': {
        \ 'buffercurrent': 'tabsel',
        \ },
    \ 'component_function': {
        \ 'bufferbefore': 'lightline#buffer#bufferbefore',
        \ 'bufferafter': 'lightline#buffer#bufferafter',
        \ 'bufferinfo': 'lightline#buffer#bufferinfo',
        \ },
    \ }
```

Thank you! Looking forward to your reply!

**Comment by fdietze** [comment]
Wow, you are right. I reported the bug for the wrong project. I'm very sorry for that. I'm using your plugin now, which works well. Thank you!
