### ISSUE TITLE
Clickable Buffers?

### ISSUE THREAD

**Issue by KingEdwardI** [taohex/lightline-buffer#5]
After finding lightline, I was hooked, and this just made it that much better. 
However it would be nice to have clicking available as I'm used to with the tabline.

As it turns out, at least with NeoVim, this is available:
https://github.com/vim-airline/vim-airline/issues/369
https://github.com/vim-airline/vim-airline/pull/1020

**Comment by taohex** [comment]
Hi, @KingEdwardI,
If you are using tab (not buffer) in your vim workflow, why not just enable the standard tabline in lightline?

**Comment by taohex** [comment]
Clickable buffers works in recent NeoVim. I am working on it. Thanks!
